# Generated by Django 3.1 on 2020-08-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='last',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='aadhar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
    ]
