# Generated by Django 3.1 on 2020-08-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_auto_20200812_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='aadhar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobilenumber',
            field=models.CharField(max_length=20),
        ),
    ]
