# Generated by Django 3.1 on 2020-08-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_auto_20200812_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('quality', models.CharField(max_length=5)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
