# Generated by Django 3.1 on 2020-08-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0005_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
