# Generated by Django 3.1 on 2020-08-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_donate_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('requestcount', models.IntegerField()),
                ('donatedcount', models.IntegerField()),
            ],
        ),
    ]
